import { z } from "zod";

export const interfaceSchema = z.object({
  ".id": z.string(),
  "actual-mtu": z.string(),
  "default-name": z.string().optional(),
  disabled: z.string(),
  "fp-rx-byte": z.string(),
  "fp-rx-packet": z.string(),
  "fp-tx-byte": z.string(),
  "fp-tx-packet": z.string(),
  l2mtu: z.string().optional(),
  "last-link-up-time": z.string(),
  "link-downs": z.string(),
  "mac-address": z.string(),
  mtu: z.union([z.string(), z.literal("auto")]),
  name: z.string(),
  running: z.string(),
  "rx-byte": z.string(),
  "rx-drop": z.string(),
  "rx-error": z.string(),
  "rx-packet": z.string(),
  "tx-byte": z.string(),
  "tx-drop": z.string(),
  "tx-error": z.string(),
  "tx-packet": z.string(),
  "tx-queue-drop": z.string(),
  type: z.string(),
});
