@auth=http://localhost:4000/auth/sign-in
@url=http://localhost:4000/rdns-records

### Sign In as Admin
# @name signInAdmin
POST {{auth}} HTTP/1.1
Content-Type: application/json

{
    "username": "johndoe1111",
    "password": "Password1111*!"
}


### Sign In as User
# @name signInUser
POST {{auth}} HTTP/1.1
Content-Type: application/json

{
    "username": "johndoe1732",
    "password": "Password1732*!"
}

### get PTR Host
# @name getPTRHost
GET {{url}}?limit=100 HTTP/1.1
Authorization: Bearer {{signInAdmin.response.body.response.tokens.accessToken.token}}

### Get PTR Host
# @name getPTRHostforUser
GET {{url}}?limit=100 HTTP/1.1
Authorization: Bearer {{signInUser.response.body.response.tokens.accessToken.token}}

### Update PTR Record
# @name updatePTRRecord
PATCH {{url}}/515283400?domainName=73.143.185.in-addr.arpa&host=2&record=21webhostingdunyasi.com HTTP/1.1
Authorization: Bearer {{signInUser.response.body.response.tokens.accessToken.token}}