@auth=http://localhost:4000/auth
@url=http://localhost:4000/ip-categories

### Sign Up
# @name signUp
POST {{auth}}/sign-up HTTP/1.1
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "username": "johndoe1732",
    "email": "johndoe1732@mail.com",
    "phoneNumber": "5439561732",
    "password": "Password1732*!"
}

### Sign In as Admin
# @name signInAdmin
POST {{auth}}/sign-in HTTP/1.1
Content-Type: application/json

{
    "username": "johndoe1111",
    "password": "Password1111*!"
}

### Sign In as User
# @name signInUser
POST {{auth}}/sign-in HTTP/1.1
Content-Type: application/json

{
    "username": "johndoe1732",
    "password": "Password1732*!"
}

### Create IP Category
# @name createIPCategory
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{signInAdmin.response.body.response.tokens.accessToken.token}}

{
    "title": "Category 8",
    "description": "Category 8 Description"
}

### Get IP Categories
# @name getIPCategories
GET {{url}} HTTP/1.1
Authorization: Bearer {{signInAdmin.response.body.response.tokens.accessToken.token}}

### Get IP Category By ID
# @name getIPCategoryByID
GET {{url}}/4 HTTP/1.1
Authorization: Bearer {{signInAdmin.response.body.response.tokens.accessToken.token}}

### Update IP Category
# @name updateIPCategory
PATCH {{url}}/5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{signInAdmin.response.body.response.tokens.accessToken.token}}

{
    "title": "Category 5 Updated",
    "description": "Category 5 Description Updated"
}